### ISSUE TITLE
Colors and formatted texts do not work on some known terminals

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#126]
We need ability to detect colors and formatting support in terminal and then decide to enable or disable this support in Nancy.

**Comment by NikolayS** [comment]
What kind of terminals have you checked?  zsh?

**Comment by NikolayS** [comment]
I think enabling/disabling will lead us to having too many options – the list is big already. Instead, we could analyze the current environment better (at bootstrap time) and define whether or not to use coloring. What do you think?

Also, how this task would look like in case if we migrated Golang or Python?

**Comment by Nastradamus** [comment]
We may take a terminal without coloring support and test a code which auto-detects support (I have an example how to do it in Bash).

>Also, how this task would look like in case if we migrated Golang or Python?
As I remember there is no problem to detect it by OS-level. Shell example:
```
#!/bin/sh
YELLOW=`tput md AF 3 2>/dev/null` || :
RESET=`tput me 2>/dev/null` || :
info () { echo "${YELLOW}INFO${RESET}: $@" >&2; }
info
```
