### ISSUE TITLE
ERROR is not last message in the output, but exit code is "1"

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#127]
I think it is good practice to have a stack of errors printed as last part of STDERROR, after STDOUT.
Or at least just print main error at the end of an output.

**Comment by NikolayS** [comment]
Agreed, we need to repeat the error message in the end, before exiting with positive code.
However, I tend to think that the original message should also remain in its original place – it can be very helpful in debugging (to see where exactly it occurred).
