### ISSUE TITLE
Choose instance name via CLI

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#128]
For better understanding what is happening in Amazon web console, it is better to add posibility to give names for an EC2 instances via Nancy CLI.

Docker?

**Comment by NikolayS** [comment]
`--amazonec2-endpoint`? https://docs.docker.com/machine/drivers/aws/#environment-variables

**Comment by Nastradamus** [comment]
@NikolayS what about mentioning in README.md about this Docker abilities ?

**Comment by NikolayS** [comment]
Right now, it's available in AWS CLI, but not in Nancy CLI. So first we need to implement it.

**Comment by NikolayS** [comment]
Also, for local runs (`--run-on localhost`), we can use this: https://docs.docker.com/engine/reference/run/#container-identification to assign custom names to local containers.

**Comment by Nastradamus** [comment]
I thing there will be a lot of users who do not understand Docker or Amazon-related settings. Even for me it was pain at first time :)

**Comment by NikolayS** [comment]
Agreed. So the idea is to have our own Nancy CLI option – say, `--name` and then map it docker/AWS CLI options.
