### ISSUE TITLE
Docker/AWS message about connection credentials should be last in stdout

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#130]
It would be nice to have a message with connection credentionals as a last part of STDOUT.

**Comment by NikolayS** [comment]
Agreed, we need to repeat the error message in the end, before exiting with positive code.
However, I tend to think that the original message should also remain in its original place – it can be very helpful in debugging (to see where exactly it occurred).

**Comment by NikolayS** [comment]
This has some conflict with https://github.com/postgres-ai/nancy/issues/127

If we've set `--keep-alive` and an error occurred, what should be the last one?
