### ISSUE TITLE
Scenario file for pgbench CLI options for nancy_run.sh

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#132]
Posibility to setup pgbench scenario via Nancy CLI/config.

**Comment by NikolayS** [comment]
Right now, it is possible to pass any pgbadger's options via string.
What we are missing, I think, is ability to use `-f` with filename where SQL for pgbench is defined.

In this case, we need to find how to process that file. For other filenames, we use `file://` / `s3://` prefixes. Maybe we need to consider the same here, but before bypassing the option string to pgBadger, we'll need to copy the file to the local FS and then substitute the prefixed file name in pgbadger option string with corresponding local file name.

**Comment by dmius** [comment]
We decided parse existing --workload-pgbench option to find where -f and filename.
