### ISSUE TITLE
Ability to disable pgBadger reports

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#133]
We don't need pgbadger on every Nancy run.

**Comment by NikolayS** [comment]
This is a small item and can be done easily – say, with `--no-pgbadger` option. However, I'm not sure if we need to disable it by default. In most cases, it's needed.

**Comment by NikolayS** [comment]
in this case, we should also disable extensive logging (first of all, this: https://github.com/postgres-ai/nancy/blob/master/docker/postgresql_10_tweak.conf#L27).

**Comment by NikolayS** [comment]
Also, in this case, it would be awesome not to lose query stats in Summary. We can grab (at least some numbers) from pg_stat_statements view.
