### ISSUE TITLE
Prewarm in Nancy?

### ISSUE THREAD

**Issue by Nastradamus** [postgres-ai/nancy#136]
Do we need pg_prewarm support in Nancy? Or other techniques?

**Comment by NikolayS** [comment]
Question to answer: 

- how `VACUUM ANALYZE` (we do it before any run) affects OS file cache and shared buffers?
- if we consider prewarming and the size of DB exceeds RAM significantly, how will we choose what to cache?
- isn't it better to perform an experimental run multiple times (say, 4) to get statistically reliable resuts and just disregard the results of the first time? The question is how to do it faster (especially if the workload is not read-only), but if filesystem snaphots will help, maybe this approach will be the best one?
