### ISSUE TITLE
Role "testuser" already exists

### ISSUE THREAD

**Issue by dan-aksenov** [postgres-ai/nancy#165]
When running nancy with dump and replay file:
```./nancy run --db-dump file://../bench.dump --workload-real file://../pgreplay.file```

I get this:
```
[2019-02-20T17:46:29+0300] Execute pgreplay queries...
ERROR:  role "testuser" already exists
[2019-02-20T17:46:29+0300] Abnormal termination. Check artifacts to understand the reasons.
```
As I see it comes from dockerfile, since I have no such user in my dump.

**Comment by Nastradamus** [comment]
@dan-aksenov thank you for reporting!

We fixed this issue in the master branch. Could you please git pull and run it again?

**Comment by dan-aksenov** [comment]
Yeh. Looks like it's working now.
