### ISSUE TITLE
EBS volumes for experimental runs

### ISSUE THREAD

**Issue by NikolayS** [postgres-ai/nancy#33]
if it's not i3 instance, 
 - [x] 1) evaluate of disk space required (using the size of Postgres DB dump provided)

 - [x] 3) in spot request, request an EBS volume as qell

**Comment by dmius** [comment]
`sudo apt install -y awscli jq`
`aws ec2 create-volume --size 10 --region us-east-1 --availability-zone us-east-1a --volume-type gp2`
`aws ec2 attach-volume --device /dev/xvdf --volume-id vol-076bd4c1c0b6e1fdf --instance-id $(curl -s http://169.254.169.254/latest/meta-data/instance-id) --region us-east-1`

```root@35b88d532c1e:/# sudo mkfs.ext4 /dev/xvdf
mke2fs 1.42.13 (17-May-2015)
The file /dev/xvdf does not exist and no size was specified.```

**Comment by dmius** [comment]
http://peteris.rocks/blog/persisting-state-between-aws-ec2-spot-instances/

**Comment by dmius** [comment]
https://github.com/startupturbo/nancy/pull/39

**Comment by NikolayS** [comment]
done?

**Comment by dmius** [comment]
Yes, merged
