### ISSUE TITLE
Baseline benchmark

### ISSUE THREAD

**Issue by NikolayS** [postgres-ai/nancy#94]
@CyberDem0n pointed to the problem: the results of experimental runs from 2 different EC2 instances might vary because it's really rare when characteristics of 2 instances are very close to each over (due multi-tenancy, hardware differences, etc). This is especially true for lower-end instances (**.large, **.xlarge, **.2xlarge).

While making the series of experimental runs on the same instance / same container is a separate topic worth to explore more, we can develop some tooling to understand the general performance of a freshly-obtained instance – we can run some "baseline benchmark" checking CPU, RAM, disk performance and then use it during the comparison for 2 (or more) experimental runs. The results of such benchmark are to be displayed in the run's summary. If we see that results difference is high, it's a signal that experiment (or a single run) has to be repeated.

Additionally, we can collect knowledge about "normal" results of baseline benchmark – "draw the baseline" – and if an instance shows poor performance ("below the baseline") we can immediately decide that we need to drop this instance and request another instance.

/cc @dmius @myyorick

**Comment by NikolayS** [comment]
helpful: http://www.brendangregg.com/blog/2017-12-31/reinvent-netflix-ec2-tuning.html

**Comment by startupturbo** [comment]
might be useful: https://www.nutanix.com/products/tools-and-technologies/x-ray/

**Comment by dmius** [comment]
А вот здесь про sysbench речь https://habr.com/company/simbirsoft/blog/271485/

**Comment by dmius** [comment]
@NikolayS Нам что вообще надо проверять?

**Comment by startupturbo** [comment]
We need to answer the general question:  "do we have CPU, memory, disk and (optionally) network resources as expected for this type of instance?"

How exactly to check every piece of it – it's an open question. I thought that either Netflix (http://www.brendangregg.com/blog/2017-12-31/reinvent-netflix-ec2-tuning.html) or Nutanix (https://www.nutanix.com/products/tools-and-technologies/x-ray/) works could be helpful here

**Comment by NikolayS** [comment]
We need to answer the general question:  "do we have CPU, memory, disk and (optionally) network resources as expected for this type of instance?"

How exactly to check every piece of it – it's an open question. I thought that either Netflix (http://www.brendangregg.com/blog/2017-12-31/reinvent-netflix-ec2-tuning.html) or Nutanix' X-Ray tool (https://www.nutanix.com/products/tools-and-technologies/x-ray/) works could be helpful here
